application: eightpoclub
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /fonts
  static_dir: static/fonts

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /img
  static_dir: static/img

- url: /.*
  script: gb.app

libraries:
- name: webapp2
  version: latest
- name: django
  version: latest